version: '3.8'

networks:
  local_ip:
    ipam:
      driver: default
      config:
        - subnet: 10.41.0.0/24

services:
  database:
    image: 'jc21/mariadb-aria:latest'
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'Tamthao@6693'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Tamthao@6693'
    volumes:
      - '/home/opc/docker/nginx/data/mysql:/var/lib/mysql'
    networks:
      local_ip:
        ipv4_address: 10.41.0.3
  nginx:
    depends_on: [mariadb]
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NPM
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: 'database'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'admin'
      DB_MYSQL_PASSWORD: 'Tamthao@6693'
      DB_MYSQL_NAME: 'npm'
    volumes:
      - '/home/opc/docker/nginx/data:/data'
      - '/home/opc/docker/nginx/letsencrypt:/etc/letsencrypt'
    networks:
      local_ip:
        ipv4_address: 10.41.0.4

  unbound:
    image: 'crazymax/unbound:latest'
    container_name: unbound
    restart: unless-stopped
    volumes:
      - '/home/opc/docker/unbound/config:/config'
    ports:
      - '5335:5335'
    networks:
      local_ip:
        ipv4_address: 10.41.0.5
  
  adguardhome:
    depends_on: [unbound]
    image: adguard/adguardhome:latest
    container_name: adguardhome
    ports:
      - '8080:80' # HTTP port
      - '8443:443' # Port for DNS-over-HTTPS
      - '853:853/tcp' # Port for DNS-over-TLS
      - '3000:3000/tcp' # AdguardHome configuration port
    volumes:
      - '/home/opc/docker/AdGuard/work:/opt/adguardhome/work'
      - '/home/opc/docker/AdGuard/conf:/opt/adguardhome/conf'
    restart: unless-stopped
    networks:
      local_ip:
        ipv4_address: 10.41.0.6
  
  wg-easy:
    depends_on: [adguardhome]
    environment:
      - WG_HOST= # Server's domain or IP
      - PASSWORD= # Input your password
      - WG_PORT=15296
      - WG_DEFAULT_ADDRESS=10.6.0.x
      - WG_DEFAULT_DNS=10.41.0.6
    image: 'weejewel/wg-easy:latest'
    container_name: wireguard
    ports:
      - '15296:51820/udp' # Wireguard using UDP, the Web UI port (51281/tcp) is omitted
    volumes:
      - '/home/opc/docker/wireguard:/etc/wireguard'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 10.41.0.6
    networks:
      local_ip:
        ipv4_address: 10.41.0.7
