version: "3.8"

networks:
  default:
    external:
      name: fukuroaki
  fukuroaki:
    external: true

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    ports:
      - "853:853/tcp" # Port for DNS-over-TLS
      - "3000:3000/tcp" # AdguardHome configuration port
    volumes:
      - "/home/ubuntu/docker/AdGuard/work:/opt/adguardhome/work"
      - "/home/ubuntu/docker/AdGuard/conf:/opt/adguardhome/conf"
    restart: unless-stopped
    networks:
      fukuroaki:
        ipv4_address: 10.41.94.5

  wg-easy:
    depends_on: [adguardhome]
    environment:
      - WG_HOST= # Server's domain or IP
      - PASSWORD= # Input your password
      - WG_PORT=15296
      - WG_DEFAULT_ADDRESS=10.6.0.x
      - WG_DEFAULT_DNS=10.41.94.5
    image: "weejewel/wg-easy:latest"
    container_name: wireguard
    ports:
      - "15296:51820/udp" # Wireguard using UDP, the Web UI port (51281/tcp) is omitted
    volumes:
      - "/home/ubuntu/docker/wireguard:/etc/wireguard"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 10.41.94.5
    networks:
      fukuroaki:
        ipv4_address: 10.41.94.6
