name: Cloudflare Gateway

on:
  # schedule:
  #   - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  deploy:
    name: Cloudflare List
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -y install wget curl jq
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Updating Cloudflare Gateway List
      run: |
        export CF_ID="${{ secrets.CF_ID }}"
        export CF_AC="${{ secrets.CF_AC }}"
        export CF_TOKEN="${{ secrets.CF_TOKEN }}"
        bash cfgateway.sh
