name: Cloudflare Gateway

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    name: Cloudflare List
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build docker
      run: docker build . --file Dockerfile --tag cf-fukuro:latest && docker run -e CF_ID="${{ secrets.CF_ID }}" -e CF_AC="${{ secrets.CF_AC }}" -e CF_TOKEN="${{ secrets.CF_TOKEN }}" cf-fukuro:latest
      env:
        ARGS: "-av"