name: Cloudflare Gateway

on:
  schedule:
    - cron: 0 6 */10 * *'
  workflow_dispatch:

jobs:
  deploy:
    name: Cloudflare List
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -y install wget curl jq
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    - name: Updating Cloudflare Gateway List
      env:
        CF_ID: ${{ secrets.CF_ID }}
        CF_AC: ${{ secrets.CF_AC }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
      run: bash bash/cfgateway.sh
